### ISSUE TITLE
who can offer vgg16_caffe.pth?

### ISSUE THREAD

**Issue by skybird1995** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#13]
caffe_pretrain = True
caffe_pretrain_path = '/home/aditya-tyco/Desktop/aditya_personal_projects/head_detection_v5/data/pretrained_model/vgg16_caffe.pth'

where is vgg16_caffe.pth?
who can offer vgg16_caffe.pth?

**Comment by aditya-vora** [comment]
@skybird1995 you need to download the pre-trained Caffe VGG16 weights from the link provided in the README. After downloading the weights of the pre-trained model you need to provide the path of that weight file on your local machine to this `caffe_pretrain_path`.

**Comment by skybird1995** [comment]
thank you very much
