### ISSUE TITLE
the problem of the train code

### ISSUE THREAD

**Issue by silencezx** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#18]
the code of train.py inlcude hollywood and brainwash datesheet,but the link just can downlowd the brainwash datasheet,could cou please shaee you datesheet with me?Thanks,....My email:zhangxingnet@sina.com,

**Comment by aditya-vora** [comment]
Please do a google search for hollywood dataset to get the link. I cannot share such huge files.
