### ISSUE TITLE
No matching distribution found for cupy-cuda80

### ISSUE THREAD

**Issue by justein** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#2]
does it can be run in win? my CUDA is 8.0 and other works well .but can not pip install cupy-cuda80

**Comment by aditya-vora** [comment]
@justein I am not sure whether cupy runs on windows. As it can be seen from their official documentation it only supports Ubuntu and CentOS. Kindly refer to this link for more installation details. 
[https://docs-cupy.chainer.org/en/stable/install.html#recommended-environments](url)

**Comment by justein** [comment]
@aditya-vora OK，I just downloading the cupy-cuda80.whl， while installing it，I got the error:does not support this platform.
My PC env:win7 64 , Nvidia GTX 940 ，python 3.5.3

**Comment by aditya-vora** [comment]
Please use it on Ubuntu as listed out in the instructions for installation.
