### ISSUE TITLE
Error when running demo

### ISSUE THREAD

**Issue by piddnad** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#22]
When I run demo, I get error message as follows:

```
Traceback (most recent call last):
  File "head_detection_demo.py", line 69, in <module>
    detect(args.img_path, args.model_path)
  File "head_detection_demo.py", line 42, in detect
    head_detector = Head_Detector_VGG16(ratios=[1], anchor_scales=[2,4])
  File "/home/kxy/FCHD-Fully-Convolutional-Head-Detector/src/head_detector_vgg16.py", line 40, in __init__
    extractor = decom_vgg16()
  File "/home/kxy/FCHD-Fully-Convolutional-Head-Detector/src/head_detector_vgg16.py", line 17, in decom_vgg16
    model.load_state_dict(t.load(opt.caffe_pretrain_path))
  File "/home/kxy/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 301, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/aditya-tyco/Desktop/aditya_personal_projects/head_detection_v5/data/pretrained_model/vgg16_caffe.pth'
```
When I look into **head_detector_vgg16.py**, I find codes like this
```
    if opt.caffe_pretrain:
        # Load the caffe model
        model = vgg16(pretrained=False)
        model.load_state_dict(t.load(opt.caffe_pretrain_path))
    else:
        # Load the default model in PyTorch
        model = vgg16(pretrained=True)
```
I think maybe something wrong when running these codes, but I don't know why.

**Comment by zrl4836** [comment]
hello , you can check the src/config.py at line 10 about caffe pre-trained VGG16

**Comment by zrl4836** [comment]
那个预训练模型需要下载后修改config.py里的路径

**Comment by Piddnad** [comment]
So if I want to run demo, I need to edit 'config.py' and let 'caffe_pretrain = False'?

> 那个预训练模型需要下载后修改config.py里的路径

**Comment by Piddnad** [comment]
I have edited 'config.py' and let `caffe_pretrain = False`
But when I run demo, I found the output images without bounding boxes.
Here is my 'config.py'. Is there any wrong in it? 
```
    caffe_pretrain = False
    caffe_pretrain_path = '/home/kxy/FCHD-Fully-Convolutional-Head-Detector/checkpoints/head_detector_final'
```

**Comment by zrl4836** [comment]
你好，你的问题解决了吗？
我同样也是在远程服务器运行我的代码。我修改【config.py】其中的代码
` caffe_pretrain = True
  caffe_pretrain_path = '下载的预训练模型【vgg16_caffe.pth】'
  model_save_path = '下载的预训练模型路径【head_detector_final】'
  test_output_path='输出结果存储在本地的路径'`
修改这一行代码在【head_detection_demo.py】
`SAVE_FLAG = 1`
[最后，根据Issue#15修改两行代码](https://github.com/aditya-vora/FCHD-Fully-Convolutional-Head-Detector/issues/15)，这样子就能准确运行了

**Comment by Piddnad** [comment]
@zrl4836 我已经成功运行了demo（修改了参数，也看到你说的那个Issue并按照里面的方法修改了代码），但同样也谢谢你的帮助！:)
另外提一下，为什么不加代码会有Bounding Box移位的问题呢，不太理解。。

**Comment by zrl4836** [comment]
这个我还没去认真理解代码。
其实这两行代码上下对换就可以了，作者应该是想获取转置之后的长宽比进行预测
`_, H, W = img.shape`
`img = img.transpose((2,0,1))`
另外我发现最后的输出结果的图片尺寸变了，
如果在原来的640*480图片绘画框就应该不会移位。
我还没进行测试，这只是我的猜测。 @Piddnad

**Comment by x2ss** [comment]
> @zrl4836 Get，我再好好理解一下代码。谢谢分享。

Hello Pddnad, I am little puzzled with the code:
caffe_pretrain = True
caffe_pretrain_path = '下载的预训练模型【vgg16_caffe.pth】
model_save_path = '下载的预训练模型路径【head_detector_final】
test_output_path='输出结果存储在本地的路径'

would you please show me the code you run successfully?
Thank you very much!

**Comment by x2ss** [comment]
> @zrl4836 我已经成功运行了demo（修改了参数，也看到你说的那个Issue并按照里面的方法修改了代码），但同样也谢谢你的帮助！:)
> 另外提一下，为什么不加代码会有Bounding Box移位的问题呢，不太理解。。

你好，我只把vgg16_caffe.pth加到caffe_pretrain_path的话，得不到带框的图，这个和issue#3 [](https://github.com/aditya-vora/FCHD-Fully-Convolutional-Head-Detector/issues/3)一样，而且，我按照根据Issue#15修改两行代码link，修改后得到的图是空白，不知道你遇到过这个问题没有。

打扰你了，十分感谢！

**Comment by x2ss** [comment]
> @zrl4836 我已经成功运行了demo（修改了参数，也看到你说的那个Issue并按照里面的方法修改了代码），但同样也谢谢你的帮助！:)
> 另外提一下，为什么不加代码会有Bounding Box移位的问题呢，不太理解。。

你好，我只把vgg16_caffe.pth加到caffe_pretrain_path的话，得不到带框的图，这个和[issue#3 ](https://github.com/aditya-vora/FCHD-Fully-Convolutional-Head-Detector/issues/3)一样，但是被作者close了。

而且，我按照根据Issue#15修改两行代码link，修改后得到的图是空白，不知道你遇到过这个问题没有。

打扰你了，十分感谢！

**Comment by x2ss** [comment]
> @zrl4836 Get，我再好好理解一下代码。谢谢分享。

你好，我只把vgg16_caffe.pth加到caffe_pretrain_path的话，得不到带框的图，这个和[issue#3](https://github.com/aditya-vora/FCHD-Fully-Convolutional-Head-Detector/issues/3)一样，但是被作者close了。

而且，我按照根据修改[issue#15](https://github.com/aditya-vora/FCHD-Fully-Convolutional-Head-Detector/issues/15)两行代码，修改后得到的图是空白，不知道你遇到过这个问题没有。


打扰你了，十分感谢！

**Comment by x2ss** [comment]
Hi zrl4836 and Piddnad, 
Thanks for sharing. 
Wish you good luck.

**Comment by MuadDev** [comment]
Hi, 
Is it possible to provide the solution above in english?
Cheers!

**Comment by Piddnad** [comment]
1. Edit 'config.py':
`caffe_pretrain = True`
` caffe_pretrain_path = 'path of [vgg16_caffe.pth]'`
` model_save_path = 'path of [head_detector_final]'`
`test_output_path='the path you want your model to save to'`
2. Edit 'head_detection_demo.py':
`SAVE_FLAG = 1`
3. Finally，refer to Issue#15 and edit those two line[link](https://github.com/aditya-vora/FCHD-Fully-Convolutional-Head-Detector/issues/15),and in the way you will run demo successfully! @ @MuadDev

**Comment by FarisHijazi** [comment]
Could somebody please share the weights of the pretrained model? it seems to have been taken down
You can email me at [theefaris@gmail.com](mailto:theefaris@gmail.com) if you have the weights, thank you!
