### ISSUE TITLE
Fail to reproduce results

### ISSUE THREAD

**Issue by hyperfraise** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#3]
Was anyone able to reproduce the results advertised in pytorch ?

![test](https://user-images.githubusercontent.com/14943759/46137620-4e30f580-c24a-11e8-8153-b903107aa58c.jpg)
![test1](https://user-images.githubusercontent.com/14943759/46137622-4f622280-c24a-11e8-8d92-c06266226e35.jpg)

I got no head detections with this. I did set caffe_pretrain to False. I tried putting some multiplications and offsets in the input tensors but never got rational results.
I'm using pytorch 0.4.0.

**Comment by aditya-vora** [comment]
@hyperfraise I guess something is incorrect with your settings because I am able to detect heads for the test image. First please use the same settings that I provided in `src/config.py` file. Just change the paths of `caffe_pretrain` depending on the location where you store the model which should be downloaded from the link that I provided in the repo. Than just run `head_detection_demo.py --img_path <path to image> --model_path <path to model>`. Here is the result. 
![figure_1](https://user-images.githubusercontent.com/11326081/46145116-b8628e00-c27c-11e8-882a-691469471fad.png)

**Comment by hyperfraise** [comment]
This is my config file. Could you tell me where I went wrong please ?

`    data_root_path = '/home/damien/Documents/FCHD-Fully-Convolutional-Head-Detector/data/brainwash_raw'
    shanghai_data_root_path = '/home/damien/Documents/FCHD-Fully-Convolutional-Head-Detector/data/shanghai_tech_final/'
    test_output_path = '/home/damien/Documents/FCHD-Fully-Convolutional-Head-Detector/output'
    min_size = 600  # image resize
    max_size = 1000 # image resize

    # sigma for l1_smooth_loss
    rpn_sigma = 3.

    weight_decay = 0.0005
    lr_decay = 0.1  # 1e-3 -> 1e-4
    lr = 1e-3

    env = 'head_detector'  # visdom env
    port = 8097
    plot_every = 100  # vis every N iter

    pretrained_model = 'vgg16'

    epoch = 15

    use_adam = False # Use Adam optimizer
    use_chainer = False # try match everything as chainer

    caffe_pretrain = False
    caffe_pretrain_path = '/home/damien/Documents/FCHD-Fully-Convolutional-Head-Detector/data/pretrained_model/vgg16_caffe.pth'
    model_save_path = '/home/damien/Documents/FCHD-Fully-Convolutional-Head-Detector/checkpoints'

    load_path = '/home/damien/Documents/FCHD-Fully-Convolutional-Head-Detector/checkpoints/sess:2/head_detector08120858_0.682282441835'
`

**Comment by hyperfraise** [comment]
So you can confirm it doesn't work with pytorch ?
This is my command :
```
python head_detection_demo.py --img_path test.jpg --model_path checkpoints/head_detector_final 
```

**Comment by hyperfraise** [comment]
I believe you've closed a little too soon :s

**Comment by x2ss** [comment]
> I believe you've closed a little too soon :s

I have the same problem as yours. Have you solved this problem?
