### ISSUE TITLE
what is the " shanghai_data_root_path" mean in the config.py?

### ISSUE THREAD

**Issue by FashionXu** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#4]

**Comment by FashionXu** [comment]
Hi, I don't know that argument mean. so I can't change it. Anybody can tell me ? Thank you.

**Comment by aditya-vora** [comment]
@FashionXu That argument is for different purpose. To benchmark the model accuracy on shanghaitech dataset. For the time being it is not required. So you can leave it as it is. The code for demo and training doesn't make use of it.

**Comment by FashionXu** [comment]
> @FashionXu That argument is for different purpose. To benchmark the model accuracy on shanghaitech dataset. For the time being it is not required. So you can leave it as it is. The code for demo and training doesn't make use of it.

Thank you. I have made the demo run. 

Another question. Can you give some pictures for the demo? Because when I used the pretrained model to detect, it couldn't detect any faces in the image.

**Comment by aditya-vora** [comment]
@FashionXu It should work on any image. I tested it on 500 test images of the brainwash dataset. However I will recheck my script again if it has any problem or not and get back to you in a day or two.

**Comment by FashionXu** [comment]
> @FashionXu It should work on any image. I tested it on 500 test images of the brainwash dataset. However I will recheck my script again if it has any problem or not and get back to you in a day or two.

Oh, thank you. But when i tested, it can't detect any faces even using the trained pictures. But during the training, I got a 0.1 total loss and it could recognize the faces in the test images. So i think it maybe i did something wrong when i run the demo. I hope to see somebody else's result.

**Comment by FashionXu** [comment]
I have finished to run the demo correctly by changing some codes (the ideas are from a deleted issue, i donot know why it is deleted), so i close this issue.

@aditya-vora Thank you. You have done a great job.
