### ISSUE TITLE
the problem of the Brainwash dataset

### ISSUE THREAD

**Issue by Master-cai** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#44]
I didn`t found the dataset from the link giving in the 'Training' part. Is the dataset from Stanford Digital Repository? I found this data was removed from access at the request of the depositor.

**Comment by guozhanxian** [comment]
I also can not find the dataset. Who can tell me where we can download the Brainwash training dataset?

**Comment by Master-cai** [comment]
> I also can not find the dataset. Who can tell me where we can download the Brainwash training dataset?

Leave your email and I will share with u.

**Comment by guozhanxian** [comment]
> > I also can not find the dataset. Who can tell me where we can download the Brainwash training dataset?
> 
> Leave your email and I will share with u.

My email is guozhanxian@gmail.com
Thank u! 💌

**Comment by zzy0724** [comment]
> > > I also can not find the dataset. Who can tell me where we can download the Brainwash training dataset?
> > 
> > 
> > Leave your email and I will share with u.
> 
> My email is [guozhanxian@gmail.com](mailto:guozhanxian@gmail.com)
> Thank u! 💌

can you send me the training dataset?Thankyou!
my email is 1057610223@qq.com

**Comment by ruyiweicas** [comment]
> > I also can not find the dataset. Who can tell me where we can download the Brainwash training dataset?
> 
> Leave your email and I will share with u.

ruyiwei2014@ia.ac.cn   @Master-cai  thx

**Comment by ShaoDu** [comment]
can you send me the training dataset?Thankyou!
my email is  2577414131@qq.com @Master-cai

**Comment by abhishek1390** [comment]
Hi @Master-cai 
Can you share the dataset?
Here is my email id abhishekh@relysys.co.in

**Comment by DAngolo66** [comment]
can you send me the training dataset,either?Thankyou!
452276958@qq.com
@Master-cai

**Comment by Master-cai** [comment]
reply in the same place：
Brainwash dataset  https://1drv.ms/u/s!Ak05bBUBFYikjNwAfU7Su5OEWZISHg?e=8Lwsf2

**Comment by LoryMANG** [comment]
Hi @Master-cai :
Can u share the Brainwash dataset?The link is canceled.
My email is 584238544@qq.com
Thank you very much

**Comment by Master-cai** [comment]
> Hi @Master-cai :
> Can u share the Brainwash dataset?The link is canceled.
> My email is [584238544@qq.com](mailto:584238544@qq.com)
> Thank you very much
已更新。

**Comment by HarborneD** [comment]
> 
> 
> reply in the same place：(url updated)
> Brainwash dataset https://onedrive.live.com/embed?cid=A4881501156C394D&resid=A4881501156C394D%21263365&authkey=AMC9ivB03spkuVI

This link seems dead now. 

Can someone share: danharborne@hotmail.co.uk 

Many thanks!

**Comment by zdaiot** [comment]
@Master-cai 
Can u share the Brainwash dataset?The link is canceled.
My email is zdaiot@163.com
Thank you very much

**Comment by ongsici** [comment]
Hi could you send me the brainwash dataset as well please? si.ong15@alumni.ic.ac.uk
Thanks!

**Comment by srinivas1746** [comment]
@ongsici  can you share me the dataset. [sinivasaluvala1746@gmail.com ](url)

**Comment by casiopeia3** [comment]
@ongsici  @Master-cai : Can you share me the dataset? Could you send me the brainwash dataset as well please?  Thanks My email is jovic.tenshoku@gmail.com

**Comment by golubchikov28** [comment]
Could someone please share the brainwash dataset also with me?
my email: golubchikov.ua28@gmail.com

**Comment by HtutLynn** [comment]
Can someone please share the brainwash dataset with me?
my email : htutlynnaung.cs@gmail.com

**Comment by GilbertTam** [comment]
Can someone please share the brainwash dataset with me?
my email : gilbert.tam.1104@gmail.com

**Comment by haoql** [comment]
Could someone please share the brainwash dataset also with me?
my email : lqchien@gmail.com

**Comment by edwardzjl** [comment]
> reply in the same place：(url updated)
> Brainwash dataset https://onedrive.live.com/embed?cid=A4881501156C394D&resid=A4881501156C394D%21263365&authkey=AMC9ivB03spkuVI

This url seems to be broken, can you share the dataset with me?
My email: jameszhou2108@hotmail.com

**Comment by Tamajit-Chakraborty** [comment]
> > I also can not find the dataset. Who can tell me where we can download the Brainwash training dataset?
> 
> Leave your email and I will share with u.

please send the the brainwash dataset.
My email: tamajitchakrabortyjpg@gmail.com

**Comment by jehlum** [comment]
please send me brainwash dataset aswell 
email : rehanmbl@gmail.com
Only for research purpose.

**Comment by rahmadiantio** [comment]
please send me brainwash dataset too
email : t.rahmadian@gmail.com

**Comment by haoql** [comment]
F.Y.I

<goog_1009100982>
https://drive.google.com/file/d/1PXXIRTyEAKMV8WjDEfCMdH3OHKVv_-8c/view?usp=sharing

Regards,
Chien-Le

**Comment by haoql** [comment]
F.Y.I

<http://goog_1009100982/>
https://drive.google.com/file/d/1PXXIRTyEAKMV8WjDEfCMdH3OHKVv_-8c/view?usp=sharing

Regards,
Chien-Le

**Comment by ganchunsheng** [comment]
> > > I also can not find the dataset. Who can tell me where we can download the Brainwash training dataset?
> > 
> > 
> > Leave your email and I will share with u.
> 
> My email is [guozhanxian@gmail.com](mailto:guozhanxian@gmail.com)
> Thank u! 💌

Dear, I need the brainwash dataset, can you share me a copy, Thank you vevry much,my email is gancs99@126.com

**Comment by 22wei22** [comment]
> > I also can not find the dataset. Who can tell me where we can download the Brainwash training dataset?
> 
> Leave your email and I will share with u.

can you send me the training dataset?Thankyou!
my email is 1334637558@qq.com @Master-cai

**Comment by 22wei22** [comment]
can you send me the training dataset?
my email is 1334637558@qq.com @ganchunsheng @haoql

**Comment by Isshss** [comment]
> > I also can not find the dataset. Who can tell me where we can download the Brainwash training dataset?
> 
> Leave your email and I will share with u.

Can you please share me with the dataset. Thanks.
EMAIL: shushan.hu@hubu.edu.cn

**Comment by BairagiPooja** [comment]
> > I also can not find the dataset. Who can tell me where we can download the Brainwash training dataset?
> 
> Leave your email and I will share with u.

Please share dataset with me. 
EMAIL-  poojabairagi@cdac.in
Thank you

**Comment by 1309928130** [comment]
my e-mail is enshanchen@foxmail.com, Thank you!

**Comment by FarisHijazi** [comment]
Could somebody please share the weights of the pretrained model? it seems to have been taken down
You can email me at theefaris@gmail.com if you have the weights, thank you!
