### ISSUE TITLE
The link for the model in the Google Drive is broken

### ISSUE THREAD

**Issue by YairMarom** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#64]
Can you please upload it again and update?
Thanks :)

**Comment by kadirbeytorun** [comment]
+1

**Comment by tiantt222** [comment]
+1

**Comment by rishcool** [comment]
+1

**Comment by asafDahan** [comment]
+1

**Comment by melih1996** [comment]
+1

**Comment by JeremyDH** [comment]
+1

**Comment by damon2hang** [comment]
+1

**Comment by aditya-vora** [comment]
I have fixed the links. Kindly check it. Sorry for the inconvenience.

**Comment by YairMarom** [comment]
Thank you for your reply and solution :)

**Comment by FarisHijazi** [comment]
Could somebody please share the weights of the pretrained model? it seems to have been taken down
You can email me at [theefaris@gmail.com](mailto:theefaris@gmail.com) if you have the weights, thank you!
